// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: airports.sql

package store

import (
	"context"
)

const createAirport = `-- name: CreateAirport :exec
INSERT INTO airports (id, name, city, country, coverage_status, customs_reentry_minutes, timezone)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateAirportParams struct {
	ID                    string
	Name                  string
	City                  string
	Country               string
	CoverageStatus        AirportsCoverageStatus
	CustomsReentryMinutes int32
	Timezone              string
}

func (q *Queries) CreateAirport(ctx context.Context, arg CreateAirportParams) error {
	_, err := q.db.ExecContext(ctx, createAirport,
		arg.ID,
		arg.Name,
		arg.City,
		arg.Country,
		arg.CoverageStatus,
		arg.CustomsReentryMinutes,
		arg.Timezone,
	)
	return err
}

const deleteAirport = `-- name: DeleteAirport :exec
DELETE FROM airports WHERE id = ?
`

func (q *Queries) DeleteAirport(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAirport, id)
	return err
}

const getAirport = `-- name: GetAirport :one
SELECT id, name, city, country, coverage_status, customs_reentry_minutes, timezone FROM airports WHERE id = ?
`

func (q *Queries) GetAirport(ctx context.Context, id string) (Airport, error) {
	row := q.db.QueryRowContext(ctx, getAirport, id)
	var i Airport
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.City,
		&i.Country,
		&i.CoverageStatus,
		&i.CustomsReentryMinutes,
		&i.Timezone,
	)
	return i, err
}

const listAirports = `-- name: ListAirports :many
SELECT id, name, city, country, coverage_status, customs_reentry_minutes, timezone FROM airports
`

func (q *Queries) ListAirports(ctx context.Context) ([]Airport, error) {
	rows, err := q.db.QueryContext(ctx, listAirports)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Airport
	for rows.Next() {
		var i Airport
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.City,
			&i.Country,
			&i.CoverageStatus,
			&i.CustomsReentryMinutes,
			&i.Timezone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchAirports = `-- name: SearchAirports :many
SELECT id, name, city, country, coverage_status, customs_reentry_minutes, timezone FROM airports
WHERE id LIKE ? OR city LIKE ? OR name LIKE ?
`

type SearchAirportsParams struct {
	ID   string
	City string
	Name string
}

func (q *Queries) SearchAirports(ctx context.Context, arg SearchAirportsParams) ([]Airport, error) {
	rows, err := q.db.QueryContext(ctx, searchAirports, arg.ID, arg.City, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Airport
	for rows.Next() {
		var i Airport
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.City,
			&i.Country,
			&i.CoverageStatus,
			&i.CustomsReentryMinutes,
			&i.Timezone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAirportCoverageStatus = `-- name: UpdateAirportCoverageStatus :exec
UPDATE airports SET coverage_status = ? WHERE id = ?
`

type UpdateAirportCoverageStatusParams struct {
	CoverageStatus AirportsCoverageStatus
	ID             string
}

func (q *Queries) UpdateAirportCoverageStatus(ctx context.Context, arg UpdateAirportCoverageStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateAirportCoverageStatus, arg.CoverageStatus, arg.ID)
	return err
}
