// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: itinerary_steps.sql

package store

import (
	"context"
	"database/sql"
)

const createStep = `-- name: CreateStep :exec
INSERT INTO itinerary_steps (id, itinerary_id, step_order, title, description, duration_minutes, transit_minutes, transit_method, cost)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateStepParams struct {
	ID              string
	ItineraryID     string
	StepOrder       int32
	Title           string
	Description     string
	DurationMinutes int32
	TransitMinutes  int32
	TransitMethod   sql.NullString
	Cost            sql.NullString
}

func (q *Queries) CreateStep(ctx context.Context, arg CreateStepParams) error {
	_, err := q.db.ExecContext(ctx, createStep,
		arg.ID,
		arg.ItineraryID,
		arg.StepOrder,
		arg.Title,
		arg.Description,
		arg.DurationMinutes,
		arg.TransitMinutes,
		arg.TransitMethod,
		arg.Cost,
	)
	return err
}

const deleteStep = `-- name: DeleteStep :exec
DELETE FROM itinerary_steps WHERE id = ? AND itinerary_id = ?
`

type DeleteStepParams struct {
	ID          string
	ItineraryID string
}

func (q *Queries) DeleteStep(ctx context.Context, arg DeleteStepParams) error {
	_, err := q.db.ExecContext(ctx, deleteStep, arg.ID, arg.ItineraryID)
	return err
}

const getStep = `-- name: GetStep :one
SELECT id, itinerary_id, step_order, title, description, duration_minutes, transit_minutes, transit_method, cost FROM itinerary_steps WHERE id = ? AND itinerary_id = ?
`

type GetStepParams struct {
	ID          string
	ItineraryID string
}

func (q *Queries) GetStep(ctx context.Context, arg GetStepParams) (ItineraryStep, error) {
	row := q.db.QueryRowContext(ctx, getStep, arg.ID, arg.ItineraryID)
	var i ItineraryStep
	err := row.Scan(
		&i.ID,
		&i.ItineraryID,
		&i.StepOrder,
		&i.Title,
		&i.Description,
		&i.DurationMinutes,
		&i.TransitMinutes,
		&i.TransitMethod,
		&i.Cost,
	)
	return i, err
}

const listSteps = `-- name: ListSteps :many
SELECT id, itinerary_id, step_order, title, description, duration_minutes, transit_minutes, transit_method, cost FROM itinerary_steps
WHERE itinerary_id = ?
ORDER BY step_order
`

func (q *Queries) ListSteps(ctx context.Context, itineraryID string) ([]ItineraryStep, error) {
	rows, err := q.db.QueryContext(ctx, listSteps, itineraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItineraryStep
	for rows.Next() {
		var i ItineraryStep
		if err := rows.Scan(
			&i.ID,
			&i.ItineraryID,
			&i.StepOrder,
			&i.Title,
			&i.Description,
			&i.DurationMinutes,
			&i.TransitMinutes,
			&i.TransitMethod,
			&i.Cost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStep = `-- name: UpdateStep :exec
UPDATE itinerary_steps
SET title = ?, description = ?, duration_minutes = ?, transit_minutes = ?, transit_method = ?, cost = ?
WHERE id = ? AND itinerary_id = ?
`

type UpdateStepParams struct {
	Title           string
	Description     string
	DurationMinutes int32
	TransitMinutes  int32
	TransitMethod   sql.NullString
	Cost            sql.NullString
	ID              string
	ItineraryID     string
}

func (q *Queries) UpdateStep(ctx context.Context, arg UpdateStepParams) error {
	_, err := q.db.ExecContext(ctx, updateStep,
		arg.Title,
		arg.Description,
		arg.DurationMinutes,
		arg.TransitMinutes,
		arg.TransitMethod,
		arg.Cost,
		arg.ID,
		arg.ItineraryID,
	)
	return err
}
