// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: itineraries.sql

package store

import (
	"context"
)

const createItinerary = `-- name: CreateItinerary :exec
INSERT INTO itineraries (id, airport_id, duration_hours, title, summary, min_duration_hours)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateItineraryParams struct {
	ID               string `json:"id"`
	AirportID        string `json:"airport_id"`
	DurationHours    int32  `json:"duration_hours"`
	Title            string `json:"title"`
	Summary          string `json:"summary"`
	MinDurationHours int32  `json:"min_duration_hours"`
}

func (q *Queries) CreateItinerary(ctx context.Context, arg CreateItineraryParams) error {
	_, err := q.db.ExecContext(ctx, createItinerary,
		arg.ID,
		arg.AirportID,
		arg.DurationHours,
		arg.Title,
		arg.Summary,
		arg.MinDurationHours,
	)
	return err
}

const deleteItinerary = `-- name: DeleteItinerary :exec
DELETE FROM itineraries WHERE id = ? AND airport_id = ?
`

type DeleteItineraryParams struct {
	ID        string `json:"id"`
	AirportID string `json:"airport_id"`
}

func (q *Queries) DeleteItinerary(ctx context.Context, arg DeleteItineraryParams) error {
	_, err := q.db.ExecContext(ctx, deleteItinerary, arg.ID, arg.AirportID)
	return err
}

const getItinerary = `-- name: GetItinerary :one
SELECT id, airport_id, duration_hours, title, summary, min_duration_hours FROM itineraries WHERE id = ? AND airport_id = ?
`

type GetItineraryParams struct {
	ID        string `json:"id"`
	AirportID string `json:"airport_id"`
}

func (q *Queries) GetItinerary(ctx context.Context, arg GetItineraryParams) (Itinerary, error) {
	row := q.db.QueryRowContext(ctx, getItinerary, arg.ID, arg.AirportID)
	var i Itinerary
	err := row.Scan(
		&i.ID,
		&i.AirportID,
		&i.DurationHours,
		&i.Title,
		&i.Summary,
		&i.MinDurationHours,
	)
	return i, err
}

const listItineraries = `-- name: ListItineraries :many
SELECT id, airport_id, duration_hours, title, summary, min_duration_hours FROM itineraries WHERE airport_id = ?
`

func (q *Queries) ListItineraries(ctx context.Context, airportID string) ([]Itinerary, error) {
	rows, err := q.db.QueryContext(ctx, listItineraries, airportID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Itinerary
	for rows.Next() {
		var i Itinerary
		if err := rows.Scan(
			&i.ID,
			&i.AirportID,
			&i.DurationHours,
			&i.Title,
			&i.Summary,
			&i.MinDurationHours,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItinerariesByDuration = `-- name: ListItinerariesByDuration :many
SELECT id, airport_id, duration_hours, title, summary, min_duration_hours FROM itineraries
WHERE airport_id = ? AND min_duration_hours <= ?
`

type ListItinerariesByDurationParams struct {
	AirportID        string `json:"airport_id"`
	MinDurationHours int32  `json:"min_duration_hours"`
}

func (q *Queries) ListItinerariesByDuration(ctx context.Context, arg ListItinerariesByDurationParams) ([]Itinerary, error) {
	rows, err := q.db.QueryContext(ctx, listItinerariesByDuration, arg.AirportID, arg.MinDurationHours)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Itinerary
	for rows.Next() {
		var i Itinerary
		if err := rows.Scan(
			&i.ID,
			&i.AirportID,
			&i.DurationHours,
			&i.Title,
			&i.Summary,
			&i.MinDurationHours,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItinerary = `-- name: UpdateItinerary :exec
UPDATE itineraries
SET title = ?, summary = ?, duration_hours = ?, min_duration_hours = ?
WHERE id = ? AND airport_id = ?
`

type UpdateItineraryParams struct {
	Title            string `json:"title"`
	Summary          string `json:"summary"`
	DurationHours    int32  `json:"duration_hours"`
	MinDurationHours int32  `json:"min_duration_hours"`
	ID               string `json:"id"`
	AirportID        string `json:"airport_id"`
}

func (q *Queries) UpdateItinerary(ctx context.Context, arg UpdateItineraryParams) error {
	_, err := q.db.ExecContext(ctx, updateItinerary,
		arg.Title,
		arg.Summary,
		arg.DurationHours,
		arg.MinDurationHours,
		arg.ID,
		arg.AirportID,
	)
	return err
}
