// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: logistics.sql

package store

import (
	"context"
	"database/sql"
)

const createLogistics = `-- name: CreateLogistics :exec
INSERT INTO logistics (id, airport_id, visa_notes, bag_storage_notes, reentry_notes)
VALUES (UUID(), ?, ?, ?, ?)
`

type CreateLogisticsParams struct {
	AirportID       string
	VisaNotes       sql.NullString
	BagStorageNotes sql.NullString
	ReentryNotes    sql.NullString
}

func (q *Queries) CreateLogistics(ctx context.Context, arg CreateLogisticsParams) error {
	_, err := q.db.ExecContext(ctx, createLogistics,
		arg.AirportID,
		arg.VisaNotes,
		arg.BagStorageNotes,
		arg.ReentryNotes,
	)
	return err
}

const deleteLogistics = `-- name: DeleteLogistics :exec
DELETE FROM logistics WHERE airport_id = ?
`

func (q *Queries) DeleteLogistics(ctx context.Context, airportID string) error {
	_, err := q.db.ExecContext(ctx, deleteLogistics, airportID)
	return err
}

const getLogistics = `-- name: GetLogistics :one
SELECT id, airport_id, visa_notes, bag_storage_notes, reentry_notes, last_updated FROM logistics WHERE airport_id = ?
`

func (q *Queries) GetLogistics(ctx context.Context, airportID string) (Logistic, error) {
	row := q.db.QueryRowContext(ctx, getLogistics, airportID)
	var i Logistic
	err := row.Scan(
		&i.ID,
		&i.AirportID,
		&i.VisaNotes,
		&i.BagStorageNotes,
		&i.ReentryNotes,
		&i.LastUpdated,
	)
	return i, err
}

const updateLogistics = `-- name: UpdateLogistics :exec
UPDATE logistics
SET visa_notes = ?, bag_storage_notes = ?, reentry_notes = ?, last_updated = NOW()
WHERE airport_id = ?
`

type UpdateLogisticsParams struct {
	VisaNotes       sql.NullString
	BagStorageNotes sql.NullString
	ReentryNotes    sql.NullString
	AirportID       string
}

func (q *Queries) UpdateLogistics(ctx context.Context, arg UpdateLogisticsParams) error {
	_, err := q.db.ExecContext(ctx, updateLogistics,
		arg.VisaNotes,
		arg.BagStorageNotes,
		arg.ReentryNotes,
		arg.AirportID,
	)
	return err
}
