// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type AirportsCoverageStatus string

const (
	AirportsCoverageStatusFull        AirportsCoverageStatus = "full"
	AirportsCoverageStatusLimited     AirportsCoverageStatus = "limited"
	AirportsCoverageStatusUnsupported AirportsCoverageStatus = "unsupported"
)

func (e *AirportsCoverageStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AirportsCoverageStatus(s)
	case string:
		*e = AirportsCoverageStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AirportsCoverageStatus: %T", src)
	}
	return nil
}

type NullAirportsCoverageStatus struct {
	AirportsCoverageStatus AirportsCoverageStatus `json:"airports_coverage_status"`
	Valid                  bool                   `json:"valid"` // Valid is true if AirportsCoverageStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAirportsCoverageStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AirportsCoverageStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AirportsCoverageStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAirportsCoverageStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AirportsCoverageStatus), nil
}

type Airport struct {
	ID                    string                 `json:"id"`
	Name                  string                 `json:"name"`
	City                  string                 `json:"city"`
	Country               string                 `json:"country"`
	CoverageStatus        AirportsCoverageStatus `json:"coverage_status"`
	CustomsReentryMinutes int32                  `json:"customs_reentry_minutes"`
	Timezone              string                 `json:"timezone"`
}

type Itinerary struct {
	ID               string `json:"id"`
	AirportID        string `json:"airport_id"`
	DurationHours    int32  `json:"duration_hours"`
	Title            string `json:"title"`
	Summary          string `json:"summary"`
	MinDurationHours int32  `json:"min_duration_hours"`
}

type ItineraryStep struct {
	ID              string         `json:"id"`
	ItineraryID     string         `json:"itinerary_id"`
	StepOrder       int32          `json:"step_order"`
	Title           string         `json:"title"`
	Description     string         `json:"description"`
	DurationMinutes int32          `json:"duration_minutes"`
	TransitMinutes  int32          `json:"transit_minutes"`
	TransitMethod   sql.NullString `json:"transit_method"`
	Cost            sql.NullString `json:"cost"`
}

type Logistic struct {
	ID              string         `json:"id"`
	AirportID       string         `json:"airport_id"`
	VisaNotes       sql.NullString `json:"visa_notes"`
	BagStorageNotes sql.NullString `json:"bag_storage_notes"`
	ReentryNotes    sql.NullString `json:"reentry_notes"`
	LastUpdated     time.Time      `json:"last_updated"`
}
