// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type AirportsCoverageStatus string

const (
	AirportsCoverageStatusFull        AirportsCoverageStatus = "full"
	AirportsCoverageStatusLimited     AirportsCoverageStatus = "limited"
	AirportsCoverageStatusUnsupported AirportsCoverageStatus = "unsupported"
)

func (e *AirportsCoverageStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AirportsCoverageStatus(s)
	case string:
		*e = AirportsCoverageStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AirportsCoverageStatus: %T", src)
	}
	return nil
}

type NullAirportsCoverageStatus struct {
	AirportsCoverageStatus AirportsCoverageStatus
	Valid                  bool // Valid is true if AirportsCoverageStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAirportsCoverageStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AirportsCoverageStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AirportsCoverageStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAirportsCoverageStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AirportsCoverageStatus), nil
}

type Airport struct {
	ID                    string
	Name                  string
	City                  string
	Country               string
	CoverageStatus        AirportsCoverageStatus
	CustomsReentryMinutes int32
	Timezone              string
}

type Itinerary struct {
	ID               string
	AirportID        string
	DurationHours    int32
	Title            string
	Summary          string
	MinDurationHours int32
}

type ItineraryStep struct {
	ID              string
	ItineraryID     string
	StepOrder       int32
	Title           string
	Description     string
	DurationMinutes int32
	TransitMinutes  int32
	TransitMethod   sql.NullString
	Cost            sql.NullString
}

type Logistic struct {
	ID              string
	AirportID       string
	VisaNotes       sql.NullString
	BagStorageNotes sql.NullString
	ReentryNotes    sql.NullString
	LastUpdated     time.Time
}
